import { Activity } from "@/types/activity.types"

export const ACTIVITY_DATA: Activity[] = [
  {
    id: "ACT001",
    title: "API Endpoint Development",
    type: "Development",
    category: "Backend",
    priority: "high",
    status: "in-progress",
    createdAt: "2024-01-15",
    deadline: "2024-02-28",
    assignee: "Michael Chen",
    project: "HRMS Platform Development",
    description: "Develop REST API endpoints for user authentication and authorization",
    tags: ["API", "Node.js", "Express"],
    estimatedHours: 40,
    actualHours: 28,
  },
  {
    id: "ACT002",
    title: "UI Component Library",
    type: "Design",
    category: "Frontend",
    priority: "medium",
    status: "completed",
    createdAt: "2024-01-10",
    deadline: "2024-01-25",
    assignee: "David Kim",
    project: "HRMS Platform Development",
    description: "Create reusable UI components with Tailwind CSS",
    tags: ["UI/UX", "Tailwind", "Components"],
    estimatedHours: 32,
    actualHours: 30,
  },
  {
    id: "ACT003",
    title: "Database Schema Design",
    type: "Development",
    category: "Database",
    priority: "high",
    status: "in-progress",
    createdAt: "2024-01-08",
    deadline: "2024-02-15",
    assignee: "Lisa Anderson",
    project: "HRMS Platform Development",
    description: "Design and implement normalized database schema for employee management",
    tags: ["Database", "PostgreSQL", "Schema"],
    estimatedHours: 24,
    actualHours: 18,
  },
  {
    id: "ACT004",
    title: "Mobile App Wireframes",
    type: "Design",
    category: "UI/UX",
    priority: "medium",
    status: "completed",
    createdAt: "2024-01-05",
    deadline: "2024-01-20",
    assignee: "Mark Thompson",
    project: "Mobile App Revamp",
    description: "Create detailed wireframes for mobile application screens",
    tags: ["Wireframes", "Figma", "Mobile"],
    estimatedHours: 20,
    actualHours: 22,
  },
  {
    id: "ACT005",
    title: "Cloud Infrastructure Setup",
    type: "DevOps",
    category: "Infrastructure",
    priority: "high",
    status: "in-progress",
    createdAt: "2024-01-12",
    deadline: "2024-03-01",
    assignee: "Robert Taylor",
    project: "HRMS Platform Development",
    description: "Set up AWS infrastructure with EC2, RDS, and S3",
    tags: ["AWS", "Cloud", "DevOps"],
    estimatedHours: 48,
    actualHours: 35,
  },
  {
    id: "ACT006",
    title: "Unit Testing Implementation",
    type: "Testing",
    category: "Quality Assurance",
    priority: "medium",
    status: "pending",
    createdAt: "2024-01-20",
    deadline: "2024-03-15",
    assignee: "Patricia Garcia",
    project: "HRMS Platform Development",
    description: "Implement comprehensive unit tests for core business logic",
    tags: ["Testing", "Jest", "Unit Tests"],
    estimatedHours: 36,
    actualHours: 0,
  },
  {
    id: "ACT007",
    title: "Performance Optimization",
    type: "Development",
    category: "Backend",
    priority: "high",
    status: "pending",
    createdAt: "2024-01-18",
    deadline: "2024-03-20",
    assignee: "James Wilson",
    project: "Mobile App Revamp",
    description: "Optimize API response times and database queries",
    tags: ["Performance", "Optimization", "API"],
    estimatedHours: 32,
    actualHours: 0,
  },
  {
    id: "ACT008",
    title: "User Authentication Flow",
    type: "Development",
    category: "Frontend",
    priority: "high",
    status: "in-progress",
    createdAt: "2024-01-22",
    deadline: "2024-02-25",
    assignee: "Emily Rodriguez",
    project: "HRMS Platform Development",
    description: "Implement secure authentication flow with JWT tokens",
    tags: ["Authentication", "JWT", "Security"],
    estimatedHours: 28,
    actualHours: 15,
  },
  {
    id: "ACT009",
    title: "Data Migration Script",
    type: "Development",
    category: "Database",
    priority: "medium",
    status: "pending",
    createdAt: "2024-01-25",
    deadline: "2024-04-01",
    assignee: "Christopher Moore",
    project: "Data Analytics Dashboard",
    description: "Create migration scripts for transferring legacy data",
    tags: ["Migration", "Database", "Scripts"],
    estimatedHours: 40,
    actualHours: 0,
  },
  {
    id: "ACT010",
    title: "Dashboard Analytics Integration",
    type: "Development",
    category: "Frontend",
    priority: "high",
    status: "planning",
    createdAt: "2024-01-28",
    deadline: "2024-05-15",
    assignee: "Linda Jackson",
    project: "Data Analytics Dashboard",
    description: "Integrate real-time analytics dashboard with data visualization",
    tags: ["Analytics", "Charts", "Real-time"],
    estimatedHours: 56,
    actualHours: 0,
  },
  {
    id: "ACT011",
    title: "CI/CD Pipeline Setup",
    type: "DevOps",
    category: "Infrastructure",
    priority: "medium",
    status: "completed",
    createdAt: "2024-01-02",
    deadline: "2024-01-30",
    assignee: "Oliver Brown",
    project: "Cloud Migration Project",
    description: "Configure automated deployment pipeline with GitHub Actions",
    tags: ["CI/CD", "GitHub Actions", "Automation"],
    estimatedHours: 24,
    actualHours: 26,
  },
  {
    id: "ACT012",
    title: "Responsive Design Testing",
    type: "Testing",
    category: "Quality Assurance",
    priority: "low",
    status: "pending",
    createdAt: "2024-01-30",
    deadline: "2024-04-10",
    assignee: "Diana Martinez",
    project: "Mobile App Revamp",
    description: "Test application responsiveness across different devices and screen sizes",
    tags: ["Responsive", "Testing", "Mobile"],
    estimatedHours: 20,
    actualHours: 0,
  },
]

export const ACTIVITY_TYPES = ["All Types", "Development", "Design", "DevOps", "Testing", "Documentation"]
export const ACTIVITY_CATEGORIES = ["All Categories", "Backend", "Frontend", "Database", "UI/UX", "Infrastructure", "Quality Assurance"]
export const ACTIVITY_STATUSES = ["All Status", "in-progress", "completed", "pending", "planning"]
export const ACTIVITY_PRIORITIES = ["All Priority", "high", "medium", "low"]

export const ACTIVITY_STATUS_LABELS: Record<string, string> = {
  "in-progress": "In Progress",
  completed: "Completed",
  pending: "Pending",
  planning: "Planning",
}

export const ACTIVITY_STATUS_COLORS: Record<string, string> = {
  "in-progress": "bg-blue-100 text-blue-700 border-blue-200",
  completed: "bg-green-100 text-green-700 border-green-200",
  pending: "bg-yellow-100 text-yellow-700 border-yellow-200",
  planning: "bg-purple-100 text-purple-700 border-purple-200",
}

export const ACTIVITY_PRIORITY_COLORS: Record<string, string> = {
  high: "bg-red-100 text-red-700 border-red-200",
  medium: "bg-yellow-100 text-yellow-700 border-yellow-200",
  low: "bg-green-100 text-green-700 border-green-200",
}
