import { Client } from "@/types/client.types"

export const CLIENT_DATA: Client[] = [
  {
    id: "CLI001",
    companyName: "Global Tech Solutions",
    industry: "Technology",
    contactPerson: "Sarah Johnson",
    email: "sarah.johnson@globaltech.com",
    phone: "+1 (555) 123-4567",
    address: "123 Innovation Drive, San Francisco, CA 94105",
    website: "www.globaltech.com",
    contractType: "Long-term",
    contractValue: 2500000,
    startDate: "2023-01-15",
    endDate: "2025-12-31",
    status: "active",
    employees: 150,
    projects: 12,
    rating: 4.8,
    paymentTerms: "Net 30",
    billingCycle: "Monthly",
    accountManager: "John Smith",
    lastContactDate: "2024-01-10",
    nextFollowUp: "2024-01-25",
    notes: "Premium enterprise client with ongoing software development projects.",
    services: ["Software Development", "IT Consulting", "Cloud Services"],
    documents: ["Contract_2023.pdf", "SOW_Q1_2024.pdf", "NDA_GlobalTech.pdf"],
  },
  {
    id: "CLI002",
    companyName: "Healthcare Plus Inc",
    industry: "Healthcare",
    contactPerson: "Dr. Michael Chen",
    email: "m.chen@healthcareplus.com",
    phone: "+1 (555) 234-5678",
    address: "456 Medical Center Blvd, Boston, MA 02115",
    website: "www.healthcareplus.com",
    contractType: "Annual",
    contractValue: 1800000,
    startDate: "2023-03-01",
    endDate: "2024-02-28",
    status: "active",
    employees: 200,
    projects: 8,
    rating: 4.5,
    paymentTerms: "Net 45",
    billingCycle: "Quarterly",
    accountManager: "Emily Davis",
    lastContactDate: "2024-01-08",
    nextFollowUp: "2024-01-22",
    notes: "Healthcare provider with EMR implementation and support services.",
    services: ["EMR Implementation", "Healthcare IT", "Data Analytics"],
    documents: ["Healthcare_Contract.pdf", "Compliance_Docs.pdf"],
  },
  {
    id: "CLI003",
    companyName: "Financial Services Corp",
    industry: "Finance",
    contactPerson: "Robert Williams",
    email: "r.williams@finserv.com",
    phone: "+1 (555) 345-6789",
    address: "789 Wall Street, New York, NY 10005",
    website: "www.finserv.com",
    contractType: "Project-based",
    contractValue: 850000,
    startDate: "2023-06-01",
    endDate: "2023-12-31",
    status: "completed",
    employees: 80,
    projects: 3,
    rating: 4.2,
    paymentTerms: "Net 15",
    billingCycle: "Milestone",
    accountManager: "Lisa Anderson",
    lastContactDate: "2023-12-15",
    nextFollowUp: "2024-02-01",
    notes: "Completed fintech application development project.",
    services: ["Fintech Development", "Security Audit", "Compliance"],
    documents: ["Project_Final_Report.pdf", "Invoice_Final.pdf"],
  },
  {
    id: "CLI004",
    companyName: "Retail Dynamics Ltd",
    industry: "Retail",
    contactPerson: "Jennifer Brown",
    email: "j.brown@retaildynamics.com",
    phone: "+1 (555) 456-7890",
    address: "321 Shopping Avenue, Chicago, IL 60601",
    website: "www.retaildynamics.com",
    contractType: "Retainer",
    contractValue: 1200000,
    startDate: "2023-04-01",
    endDate: "2024-03-31",
    status: "active",
    employees: 300,
    projects: 15,
    rating: 4.0,
    paymentTerms: "Net 30",
    billingCycle: "Monthly",
    accountManager: "Mark Thompson",
    lastContactDate: "2024-01-12",
    nextFollowUp: "2024-01-26",
    notes: "Retail chain with POS and inventory management solutions.",
    services: ["POS Systems", "Inventory Management", "E-commerce"],
    documents: ["Retainer_Agreement.pdf", "Service_Level_Agreement.pdf"],
  },
  {
    id: "CLI005",
    companyName: "Education First Academy",
    industry: "Education",
    contactPerson: "Patricia Garcia",
    email: "p.garcia@educationfirst.com",
    phone: "+1 (555) 567-8901",
    address: "987 Learning Lane, Austin, TX 78701",
    website: "www.educationfirst.com",
    contractType: "Annual",
    contractValue: 650000,
    startDate: "2023-09-01",
    endDate: "2024-08-31",
    status: "active",
    employees: 50,
    projects: 6,
    rating: 4.6,
    paymentTerms: "Net 60",
    billingCycle: "Quarterly",
    accountManager: "Kevin White",
    lastContactDate: "2024-01-11",
    nextFollowUp: "2024-01-24",
    notes: "Educational institution with learning management system implementation.",
    services: ["LMS Development", "Training Programs", "Support"],
    documents: ["Education_Contract.pdf", "Training_Materials.pdf"],
  },
  {
    id: "CLI006",
    companyName: "Logistics Pro Systems",
    industry: "Logistics",
    contactPerson: "David Martinez",
    email: "d.martinez@logisticspro.com",
    phone: "+1 (555) 678-9012",
    address: "147 Transport Way, Atlanta, GA 30301",
    website: "www.logisticspro.com",
    contractType: "Long-term",
    contractValue: 3200000,
    startDate: "2022-11-01",
    endDate: "2025-10-31",
    status: "active",
    employees: 180,
    projects: 20,
    rating: 4.9,
    paymentTerms: "Net 30",
    billingCycle: "Monthly",
    accountManager: "Nancy Taylor",
    lastContactDate: "2024-01-09",
    nextFollowUp: "2024-01-23",
    notes: "Major logistics company with comprehensive supply chain solutions.",
    services: ["Supply Chain Software", "Fleet Management", "Analytics"],
    documents: ["Master_Agreement.pdf", "SLA_Document.pdf", "Technical_Specs.pdf"],
  },
]

export const CLIENT_INDUSTRIES = [
  "All Industries",
  "Technology",
  "Healthcare",
  "Finance",
  "Retail",
  "Education",
  "Logistics",
  "Manufacturing",
  "Consulting",
]

export const CLIENT_STATUS_OPTIONS = ["All Status", "active", "completed", "pending", "inactive"]

export const CONTRACT_TYPES = ["All Types", "Long-term", "Annual", "Project-based", "Retainer", "Monthly"]

export const CLIENT_STATUS_LABELS: Record<string, string> = {
  active: "Active",
  completed: "Completed",
  pending: "Pending",
  inactive: "Inactive",
}

export const CLIENT_STATUS_COLORS: Record<string, string> = {
  active: "bg-green-100 text-green-800",
  completed: "bg-blue-100 text-blue-800",
  pending: "bg-yellow-100 text-yellow-800",
  inactive: "bg-red-100 text-red-800",
}
