import { Company } from "@/types/company.types"

export const COMPANY_DATA: Company[] = [
  {
    id: "CMP001",
    name: "Tech Solutions Inc.",
    industry: "Technology",
    email: "contact@techsolutions.com",
    phone: "+1 (555) 123-4567",
    address: "123 Tech Street, Silicon Valley, CA 94025",
    website: "www.techsolutions.com",
    employees: 150,
    revenue: 5000000,
    status: "active",
    foundedDate: "2015-03-15",
    description: "Leading technology solutions provider specializing in enterprise software development.",
    contact: "John Smith",
    rating: 4.5,
    ownerName: "Michael Johnson",
  },
  {
    id: "CMP002",
    name: "Global Finance Corp",
    industry: "Finance",
    email: "info@globalfinance.com",
    phone: "+1 (555) 234-5678",
    address: "456 Wall Street, New York, NY 10005",
    website: "www.globalfinance.com",
    employees: 300,
    revenue: 15000000,
    status: "active",
    foundedDate: "2010-07-20",
    description: "International financial services company offering banking and investment solutions.",
    contact: "Sarah Williams",
    rating: 4.8,
    ownerName: "Robert Davis",
  },
  {
    id: "CMP003",
    name: "Healthcare Plus",
    industry: "Healthcare",
    email: "support@healthcareplus.com",
    phone: "+1 (555) 345-6789",
    address: "789 Medical Blvd, Boston, MA 02115",
    website: "www.healthcareplus.com",
    employees: 200,
    revenue: 8000000,
    status: "active",
    foundedDate: "2012-11-10",
    description: "Comprehensive healthcare services provider with focus on patient care and medical innovation.",
    contact: "Dr. Emily Chen",
    rating: 4.2,
    ownerName: "Dr. James Wilson",
  },
  {
    id: "CMP004",
    name: "Retail Dynamics",
    industry: "Retail",
    email: "sales@retaildynamics.com",
    phone: "+1 (555) 456-7890",
    address: "321 Shopping Ave, Chicago, IL 60601",
    website: "www.retaildynamics.com",
    employees: 500,
    revenue: 25000000,
    status: "active",
    foundedDate: "2008-05-12",
    description: "Leading retail chain with stores across multiple states offering quality products at competitive prices.",
    contact: "Lisa Anderson",
    rating: 3.9,
    ownerName: "David Martinez",
  },
  {
    id: "CMP005",
    name: "Energy Systems Ltd",
    industry: "Energy",
    email: "info@energysystems.com",
    phone: "+1 (555) 567-8901",
    address: "654 Power Road, Houston, TX 77001",
    website: "www.energysystems.com",
    employees: 180,
    revenue: 12000000,
    status: "inactive",
    foundedDate: "2014-09-18",
    description: "Renewable energy solutions provider specializing in solar and wind power systems.",
    contact: "Mark Thompson",
    rating: 4.1,
    ownerName: "Jennifer Brown",
  },
  {
    id: "CMP006",
    name: "Education First",
    industry: "Education",
    email: "admin@educationfirst.com",
    phone: "+1 (555) 678-9012",
    address: "987 Learning Lane, Boston, MA 02116",
    website: "www.educationfirst.com",
    employees: 120,
    revenue: 3000000,
    status: "active",
    foundedDate: "2016-02-28",
    description: "Innovative educational institution providing online and classroom-based learning programs.",
    contact: "Patricia Garcia",
    rating: 4.6,
    ownerName: "Richard Lee",
  },
  {
    id: "CMP007",
    name: "Logistics Pro",
    industry: "Logistics",
    email: "service@logisticspro.com",
    phone: "+1 (555) 789-0123",
    address: "147 Transport Way, Atlanta, GA 30301",
    website: "www.logisticspro.com",
    employees: 250,
    revenue: 9000000,
    status: "active",
    foundedDate: "2011-12-05",
    description: "Comprehensive logistics and supply chain management solutions for businesses of all sizes.",
    contact: "Kevin White",
    rating: 4.3,
    ownerName: "Maria Rodriguez",
  },
  {
    id: "CMP008",
    name: "Food & Beverage Co",
    industry: "Food & Beverage",
    email: "orders@foodbeverage.com",
    phone: "+1 (555) 890-1234",
    address: "258 Culinary Drive, Los Angeles, CA 90001",
    website: "www.foodbeverage.com",
    employees: 350,
    revenue: 18000000,
    status: "active",
    foundedDate: "2013-06-15",
    description: "Premium food and beverage company specializing in organic and natural products.",
    contact: "Nancy Taylor",
    rating: 4.7,
    ownerName: "Thomas Anderson",
  },
  {
    id: "CMP009",
    name: "Real Estate Masters",
    industry: "Real Estate",
    email: "info@realestatemasters.com",
    phone: "+1 (555) 901-2345",
    address: "369 Property Blvd, Miami, FL 33101",
    website: "www.realestatemasters.com",
    employees: 80,
    revenue: 6000000,
    status: "active",
    foundedDate: "2017-08-22",
    description: "Full-service real estate company offering residential and commercial property solutions.",
    contact: "Christopher Moore",
    rating: 4.0,
    ownerName: "Linda Jackson",
  },
]

export const INDUSTRIES = [
  "All Industries",
  "Technology",
  "Finance",
  "Healthcare",
  "Retail",
  "Energy",
  "Education",
  "Logistics",
  "Food & Beverage",
  "Real Estate",
]

export const COMPANY_STATUS_OPTIONS = ["All Status", "active", "inactive"]
