import type { Holiday, HolidayStatCardConfig, HolidayTypeBadgeConfig } from "@/types/holiday.types"

export const HOLIDAY_STAT_CARDS: HolidayStatCardConfig[] = [
  {
    key: "totalHolidays",
    label: "Total Holidays",
    badgeLabel: "Total",
    icon: "Calendar",
    gradient: "from-blue-500 to-blue-600",
    shadow: "shadow-blue-500/25",
    badgeBg: "bg-blue-50 dark:bg-blue-950/30",
    badgeText: "text-blue-600 dark:text-blue-400",
  },
  {
    key: "publicHolidays",
    label: "Public Holidays",
    badgeLabel: "Public",
    icon: "Sparkles",
    gradient: "from-emerald-500 to-emerald-600",
    shadow: "shadow-emerald-500/25",
    badgeBg: "bg-emerald-50 dark:bg-emerald-950/30",
    badgeText: "text-emerald-600 dark:text-emerald-400",
  },
  {
    key: "companyHolidays",
    label: "Company Holidays",
    badgeLabel: "Company",
    icon: "TrendingUp",
    gradient: "from-violet-500 to-violet-600",
    shadow: "shadow-violet-500/25",
    badgeBg: "bg-violet-50 dark:bg-violet-950/30",
    badgeText: "text-violet-600 dark:text-violet-400",
  },
  {
    key: "optionalHolidays",
    label: "Optional Holidays",
    badgeLabel: "Optional",
    icon: "Gift",
    gradient: "from-amber-500 to-amber-600",
    shadow: "shadow-amber-500/25",
    badgeBg: "bg-amber-50 dark:bg-amber-950/30",
    badgeText: "text-amber-600 dark:text-amber-400",
  },
]

export const HOLIDAY_TYPE_BADGE_MAP: Record<string, HolidayTypeBadgeConfig> = {
  public: {
    bg: "bg-blue-50",
    text: "text-blue-700",
    border: "border-blue-200",
    dark: "dark:bg-blue-950/30 dark:text-blue-400 dark:border-blue-800",
    dot: "bg-blue-500",
    label: "Public",
    gradient: "from-blue-500 to-blue-600",
  },
  company: {
    bg: "bg-emerald-50",
    text: "text-emerald-700",
    border: "border-emerald-200",
    dark: "dark:bg-emerald-950/30 dark:text-emerald-400 dark:border-emerald-800",
    dot: "bg-emerald-500",
    label: "Company",
    gradient: "from-emerald-500 to-emerald-600",
  },
  optional: {
    bg: "bg-amber-50",
    text: "text-amber-700",
    border: "border-amber-200",
    dark: "dark:bg-amber-950/30 dark:text-amber-400 dark:border-amber-800",
    dot: "bg-amber-500",
    label: "Optional",
    gradient: "from-amber-500 to-amber-600",
  },
}

export const INITIAL_HOLIDAYS: Holiday[] = [
  {
    id: "1",
    name: "New Year's Day",
    date: "2024-01-01",
    type: "public",
    duration: "full-day",
    description: "Celebration of the New Year",
    recurring: true,
  },
  {
    id: "2",
    name: "Company Foundation Day",
    date: "2024-02-15",
    type: "company",
    duration: "full-day",
    description: "Anniversary of company establishment",
    recurring: true,
  },
  {
    id: "3",
    name: "Good Friday",
    date: "2024-03-29",
    type: "public",
    duration: "full-day",
    description: "Christian religious holiday",
    recurring: true,
  },
  {
    id: "4",
    name: "Team Building Event",
    date: "2024-04-20",
    type: "company",
    duration: "half-day",
    location: "Office & Recreation Center",
    description: "Quarterly team building activities",
    recurring: false,
  },
  {
    id: "5",
    name: "Labor Day",
    date: "2024-05-01",
    type: "public",
    duration: "full-day",
    description: "International Workers' Day",
    recurring: true,
  },
  {
    id: "6",
    name: "Independence Day",
    date: "2024-07-04",
    type: "public",
    duration: "full-day",
    description: "National Independence Day",
    recurring: true,
  },
  {
    id: "7",
    name: "Summer Break",
    date: "2024-08-15",
    type: "company",
    duration: "full-day",
    description: "Company-wide summer holiday",
    recurring: true,
  },
  {
    id: "8",
    name: "Thanksgiving Day",
    date: "2024-11-28",
    type: "public",
    duration: "full-day",
    description: "National day of gratitude",
    recurring: true,
  },
  {
    id: "9",
    name: "Christmas Day",
    date: "2024-12-25",
    type: "public",
    duration: "full-day",
    description: "Christian religious celebration",
    recurring: true,
  },
]

export const YEAR_OPTIONS = ["2023", "2024", "2025"]
