import type { InventoryItem } from "@/types/inventory.types"

export const INVENTORY_DATA: InventoryItem[] = [
  {
    id: 1,
    sku: "LAP-001",
    name: "Laptop Model X",
    category: "Electronics",
    quantity: 45,
    minStock: 20,
    maxStock: 100,
    unitPrice: 1299.99,
    totalValue: 58499.55,
    location: "Warehouse A",
    supplier: "Tech Supplies Inc.",
    lastUpdated: "2024-03-15",
    status: "in-stock",
    reorderPoint: 25,
  },
  {
    id: 2,
    sku: "OFF-002",
    name: "Office Chair Pro",
    category: "Furniture",
    quantity: 18,
    minStock: 15,
    maxStock: 50,
    unitPrice: 299.99,
    totalValue: 5399.82,
    location: "Warehouse B",
    supplier: "Furniture Plus",
    lastUpdated: "2024-03-14",
    status: "low-stock",
    reorderPoint: 20,
  },
  {
    id: 3,
    sku: "PEN-003",
    name: "Wireless Mouse",
    category: "Electronics",
    quantity: 156,
    minStock: 50,
    maxStock: 200,
    unitPrice: 29.99,
    totalValue: 4678.44,
    location: "Warehouse A",
    supplier: "Tech Supplies Inc.",
    lastUpdated: "2024-03-16",
    status: "in-stock",
    reorderPoint: 60,
  },
  {
    id: 4,
    sku: "PAP-004",
    name: "A4 Paper Pack",
    category: "Office Supplies",
    quantity: 8,
    minStock: 25,
    maxStock: 100,
    unitPrice: 19.99,
    totalValue: 159.92,
    location: "Warehouse C",
    supplier: "Office Depot",
    lastUpdated: "2024-03-13",
    status: "out-of-stock",
    reorderPoint: 30,
  },
]

export const CATEGORIES = [
  "All Categories",
  "Electronics",
  "Furniture",
  "Office Supplies",
  "Raw Materials",
]

export const STATUSES = [
  "All Status",
  "in-stock",
  "low-stock",
  "out-of-stock",
]

export const STATUS_CONFIG: Record<string, { bg: string; text: string; dot: string; label: string }> = {
  "in-stock": { bg: "bg-emerald-50", text: "text-emerald-700", dot: "bg-emerald-500", label: "In Stock" },
  "low-stock": { bg: "bg-amber-50", text: "text-amber-700", dot: "bg-amber-500", label: "Low Stock" },
  "out-of-stock": { bg: "bg-red-50", text: "text-red-700", dot: "bg-red-500", label: "Out of Stock" },
}

export const TABLE_HEADERS = [
  { key: "sku", label: "SKU", align: "left" as const },
  { key: "name", label: "Item Name", align: "left" as const },
  { key: "category", label: "Category", align: "left" as const },
  { key: "quantity", label: "Quantity", align: "center" as const },
  { key: "minMax", label: "Min / Max", align: "center" as const },
  { key: "unitPrice", label: "Unit Price", align: "right" as const },
  { key: "totalValue", label: "Total Value", align: "right" as const },
  { key: "location", label: "Location", align: "left" as const },
  { key: "status", label: "Status", align: "center" as const },
  { key: "actions", label: "Actions", align: "center" as const },
]

export const STAT_CARDS = [
  {
    label: "Total Items",
    statKey: "totalItems" as const,
    subLabel: "Total Value",
    subType: "currency" as const,
    subStatKey: "totalValue" as const,
    gradient: "from-blue-50 to-indigo-50",
    border: "border-blue-200",
    textColor: "text-blue-600",
    valueColor: "text-blue-900",
    iconBg: "bg-blue-100",
    icon: "Package",
  },
  {
    label: "Low Stock",
    statKey: "lowStockCount" as const,
    subLabel: "Need reordering",
    gradient: "from-amber-50 to-yellow-50",
    border: "border-amber-200",
    textColor: "text-amber-600",
    valueColor: "text-amber-900",
    iconBg: "bg-amber-100",
    icon: "AlertTriangle",
  },
  {
    label: "Out of Stock",
    statKey: "outOfStockCount" as const,
    subLabel: "Immediate action needed",
    gradient: "from-red-50 to-rose-50",
    border: "border-red-200",
    textColor: "text-red-600",
    valueColor: "text-red-900",
    iconBg: "bg-red-100",
    icon: "Truck",
  },
  {
    label: "Total Quantity",
    statKey: "totalQuantity" as const,
    subLabel: "Across all items",
    gradient: "from-emerald-50 to-green-50",
    border: "border-emerald-200",
    textColor: "text-emerald-600",
    valueColor: "text-emerald-900",
    iconBg: "bg-emerald-100",
    icon: "BarChart3",
  },
]
