import { Project } from "@/types/project.types"

export const PROJECT_DATA: Project[] = [
  {
    id: "PRJ001",
    name: "HRMS Platform Development",
    description: "Complete overhaul of the existing HR management system with modern UI/UX and enhanced features.",
    status: "in-progress",
    priority: "high",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    progress: 65,
    employees: 8,
    projectCoordinator: "Sarah Johnson",
    projectLead: "Michael Chen",
    rating: 4.5,
    team: [
      { name: "Sarah Johnson", role: "Project Coordinator", avatar: "SJ" },
      { name: "Michael Chen", role: "Project Lead", avatar: "MC" },
      { name: "Emily Rodriguez", role: "Senior Developer", avatar: "ER" },
      { name: "David Kim", role: "UI/UX Designer", avatar: "DK" },
      { name: "Lisa Anderson", role: "Backend Developer", avatar: "LA" },
      { name: "James Wilson", role: "Frontend Developer", avatar: "JW" },
      { name: "Patricia Garcia", role: "QA Engineer", avatar: "PG" },
      { name: "Robert Taylor", role: "DevOps Engineer", avatar: "RT" },
    ],
    budget: 250000,
    client: "Global Tech Solutions",
    tags: ["Development", "HRMS", "High Priority"],
    milestones: [
      { name: "Requirements Gathering", completed: true, date: "2024-01-30" },
      { name: "Design Phase", completed: true, date: "2024-02-28" },
      { name: "Development Sprint 1", completed: true, date: "2024-03-31" },
      { name: "Development Sprint 2", completed: false, date: "2024-04-30" },
      { name: "Testing & Deployment", completed: false, date: "2024-06-15" },
    ],
  },
  {
    id: "PRJ002",
    name: "Mobile App Revamp",
    description: "Redesign and rebuild of the company mobile application with improved performance and user experience.",
    status: "completed",
    priority: "medium",
    startDate: "2023-09-01",
    endDate: "2024-01-15",
    progress: 100,
    employees: 5,
    projectCoordinator: "Jennifer Brown",
    projectLead: "Kevin White",
    rating: 4.8,
    team: [
      { name: "Jennifer Brown", role: "Project Coordinator", avatar: "JB" },
      { name: "Kevin White", role: "Project Lead", avatar: "KW" },
      { name: "Nancy Taylor", role: "Mobile Developer", avatar: "NT" },
      { name: "Mark Thompson", role: "UI Designer", avatar: "MT" },
      { name: "Diana Martinez", role: "QA Engineer", avatar: "DM" },
    ],
    budget: 180000,
    client: "Retail Dynamics Ltd",
    tags: ["Mobile", "Design", "Completed"],
    milestones: [
      { name: "Research & Planning", completed: true, date: "2023-09-30" },
      { name: "UI/UX Design", completed: true, date: "2023-10-31" },
      { name: "Development", completed: true, date: "2023-12-15" },
      { name: "Testing", completed: true, date: "2024-01-10" },
      { name: "Launch", completed: true, date: "2024-01-15" },
    ],
  },
  {
    id: "PRJ003",
    name: "Data Analytics Dashboard",
    description: "Implementation of real-time analytics dashboard for business intelligence and reporting.",
    status: "planning",
    priority: "medium",
    startDate: "2024-03-01",
    endDate: "2024-08-31",
    progress: 15,
    employees: 6,
    projectCoordinator: "Thomas Anderson",
    projectLead: "Maria Rodriguez",
    rating: 4.2,
    team: [
      { name: "Thomas Anderson", role: "Project Coordinator", avatar: "TA" },
      { name: "Maria Rodriguez", role: "Project Lead", avatar: "MR" },
      { name: "Christopher Moore", role: "Data Engineer", avatar: "CM" },
      { name: "Linda Jackson", role: "Frontend Developer", avatar: "LJ" },
      { name: "Richard Lee", role: "Backend Developer", avatar: "RL" },
      { name: "Jessica Davis", role: "Analytics Specialist", avatar: "JD" },
    ],
    budget: 320000,
    client: "Financial Services Corp",
    tags: ["Analytics", "Dashboard", "Planning"],
    milestones: [
      { name: "Requirements Analysis", completed: true, date: "2024-03-15" },
      { name: "Architecture Design", completed: false, date: "2024-04-01" },
      { name: "Data Pipeline Setup", completed: false, date: "2024-05-15" },
      { name: "Dashboard Development", completed: false, date: "2024-07-01" },
      { name: "Testing & Deployment", completed: false, date: "2024-08-15" },
    ],
  },
  {
    id: "PRJ004",
    name: "Cloud Migration Project",
    description: "Migration of legacy systems to cloud infrastructure with zero downtime strategy.",
    status: "on-hold",
    priority: "low",
    startDate: "2024-02-01",
    endDate: "2024-05-31",
    progress: 40,
    employees: 4,
    projectCoordinator: "Daniel Wilson",
    projectLead: "Sophia Chen",
    rating: 3.9,
    team: [
      { name: "Daniel Wilson", role: "Project Coordinator", avatar: "DW" },
      { name: "Sophia Chen", role: "Project Lead", avatar: "SC" },
      { name: "Oliver Brown", role: "Cloud Architect", avatar: "OB" },
      { name: "Emma Davis", role: "DevOps Engineer", avatar: "ED" },
    ],
    budget: 150000,
    client: "Healthcare Plus Inc",
    tags: ["Cloud", "Migration", "On Hold"],
    milestones: [
      { name: "Assessment & Planning", completed: true, date: "2024-02-15" },
      { name: "Infrastructure Setup", completed: true, date: "2024-03-01" },
      { name: "Data Migration", completed: false, date: "2024-04-15" },
      { name: "Testing & Validation", completed: false, date: "2024-05-15" },
      { name: "Go Live", completed: false, date: "2024-05-31" },
    ],
  },
]

export const PROJECT_STATUSES = ["All Status", "in-progress", "completed", "planning", "on-hold"]
export const PROJECT_PRIORITIES = ["All Priority", "high", "medium", "low"]
export const PROJECT_CLIENTS = [
  "All Clients",
  "Global Tech Solutions",
  "Retail Dynamics Ltd",
  "Financial Services Corp",
  "Healthcare Plus Inc",
]

export const PROJECT_STATUS_LABELS: Record<string, string> = {
  "in-progress": "In Progress",
  completed: "Completed",
  planning: "Planning",
  "on-hold": "On Hold",
}

export const PROJECT_STATUS_COLORS: Record<string, { bg: string; color: string; border: string }> = {
  "in-progress": { bg: "bg-blue-100", color: "text-blue-800", border: "border-blue-200" },
  completed: { bg: "bg-green-100", color: "text-green-800", border: "border-green-200" },
  planning: { bg: "bg-yellow-100", color: "text-yellow-800", border: "border-yellow-200" },
  "on-hold": { bg: "bg-red-100", color: "text-red-800", border: "border-red-200" },
}

export const PROJECT_PRIORITY_COLORS: Record<string, string> = {
  high: "bg-red-500",
  medium: "bg-yellow-500",
  low: "bg-green-500",
}
