"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card"
import { Button } from "@/components/ui/Button"
import { Calendar, Download, Eye, DollarSign, Package, Users, Settings, FileText } from "lucide-react"
import { RecentReport } from "@/types/reporting.types"
import { RECENT_REPORTS } from "@/constants/reporting"

interface RecentReportsListProps {
  getReportStatusColor: (status: string) => string
}

function ReportTypeIcon({ type }: { type: string }) {
  switch (type) {
    case "financial":     return <DollarSign className="w-5 h-5 text-green-600" />
    case "inventory":    return <Package className="w-5 h-5 text-blue-600" />
    case "sales":        return <Users className="w-5 h-5 text-orange-600" />
    case "manufacturing": return <Settings className="w-5 h-5 text-indigo-600" />
    default:             return <FileText className="w-5 h-5 text-gray-600" />
  }
}

export default function RecentReportsList({ getReportStatusColor }: RecentReportsListProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg font-semibold">Recent Reports</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {RECENT_REPORTS.map((report: RecentReport) => (
            <div
              key={report.id}
              className="bg-slate-50 rounded-lg p-6 border border-slate-200 hover:bg-slate-100 transition-colors"
            >
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                  <ReportTypeIcon type={report.type} />
                  <div>
                    <h3 className="text-lg font-semibold text-slate-900">{report.name}</h3>
                    <p className="text-sm text-slate-500">
                      {report.type.charAt(0).toUpperCase() + report.type.slice(1)}
                    </p>
                  </div>
                </div>
                <div className={`px-2 py-1 rounded-full text-xs font-medium ${getReportStatusColor(report.status)}`}>
                  {report.status}
                </div>
              </div>
              <div className="text-sm text-slate-700">{report.description}</div>
              <div className="flex items-center justify-between mt-4">
                <div className="flex items-center gap-2">
                  <Calendar className="w-4 h-4 text-slate-400" />
                  <span className="text-sm text-slate-700">{report.date}</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-sm text-slate-600">Generated by:</span>
                  <span className="text-sm text-slate-900">{report.generatedBy}</span>
                </div>
              </div>
              <div className="flex gap-2 mt-4">
                <Button variant="outline" className="cursor-pointer">
                  <Eye className="w-4 h-4 mr-2" />
                  View
                </Button>
                <Button className="bg-indigo-600 hover:bg-indigo-700 text-white cursor-pointer">
                  <Download className="w-4 h-4 mr-2" />
                  Download
                </Button>
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  )
}
